michaeltreat/Escape-code-201

last-page.css, last-page.html, last-page.js, style.css
Added the last page functionality!
=> Monday last page

rpg1.css, rpg1.html, rpg1.js
=> figured out question logic

last-page.css, math-challenge.css, math-challenge.html, math-challenge.js
Added the math challenge page. Still needs some CSS but all functionality is there.
=> Monday math challenge

rpg1.css, rpg1.js
=> Monday rpg

app.js, index-html.js, index.html, last-page.css, last-page.html, local-storage.js, math-challenge.css, math-challenge.html
Updated and added local storage.
=> Updated localStorage functionality

about-us.css, about-us.html
outlined form of About us page
=> Monday about us

math-challenge.css, math-challenge.html
=> Monday math stretch

casino.css, casino.html
=> Tuesday casino layout

math-challenge.css, pageTwo.css, pageTwo.html
=> Tuesday night saul

rpg1.css, rpg1.html, rpg1.js
=> questions working.  content started

rpg1.css, rpg1.js
=> linked to casino.html, fixed questions

rpg1.css, rpg1.html, rpg1.js
Working on images and context between images
=> all questions working. working on images

rpg1.js
functionality working.  still working on pictures.
=> working on page images

debugger.html
=>  added link for deployment

pageTwo.js
=>  thursday morning merge party

rpg1.css, rpg1.js
=> added confirm messages

casino.html, debugger.html, debugger.js
=> Wed debugger

rpg1.js
=> fixed ending

rpg1.js
=> changed TA question prompts

local-storage.js, pageTwo.js
=> hotfix of local storage console logs
